# Core
spring:
  application:
    name: spring-security-demo
    version: 0.0.1
  profiles.active: local
  main:
    web-environment: true

  jackson:
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
  profiles:
    active: local

---
spring:
  profiles: local

  datasource:
    dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
    url: jdbc:mysql://192.168.99.100:3306/TEST
    username: root
    password: campaign@dm1n

    poolName: PersonalizeHikariCP
    maximumPoolSize: 20
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    openInView: false
    show_sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy

    properties:
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false

server:
  port: 8095

security:
  user:
    name: test
    password: pass




